FlaskApp/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views

FlaskApp/blog/views.py
from . import blog
from ..models import *
from flask import redirect, url_for, g
from flask import render_template, request, abort, session
from jinja2 import TemplateNotFound
import peewee

@blog.route("/")
def nullblog():
    latest = Post.select().where(Post.live == True).order_by(-1*Post.date).limit(1)[0]
    return post(latest.date)

@blog.route("/<date>")
def post(date):
    index = Post.select(Post.date, Post.title).where(Post.live == True).order_by(-1*Post.date)
    try:
        post = Post.get(Post.date == date)
        if post.live or 'logged_in' in session:
            return render_template('/blogs/post.html', post=post, tags=post.tags(), index=index)
    except peewee.DoesNotExist:
        pass
    return redirect(url_for('blog.nullblog'))

@blog.route("/tag/<tagname>")
def tag(tagname):
    try:
        tag = Tag.get(Tag.name == tagname)
        taglist = Tag.select()
        return render_template(
                '/blogs/tag.html', 
                tag=tag, 
                posts=tag.posts(include_text=False).order_by(-1*Post.date), 
                taglist=taglist
                )
    except peewee.DoesNotExist:
        abort(404)

@blog.before_request
def open_db():
    g.db = database
    g.db.connect()

@blog.after_request
def close_db(response):
    g.db.close()
    return response

FlaskApp/templates/blogs/7-15-14.html
{% extends "blog.html" %}
{% block post %}
<h2>A Pure CSS Solution To Flexible Multi-Column Layouts with Background Colors</h2>
<p>
This is an infamous css problem, and there are lots of partial solutions out there that didn't suit my needs.
</p>

<p>
The goal is to have a multi-column layout, like that of this page.  In this example, the left and right columns are functioning as borders, but the problem is the same.  If the page content (this text) is long enough that the page scrolls, the columns on the left and right must at least appear to continue down the page.  If the content is less than a full page, the border columns must still reach all the way to down to the floor.
</p>

<p>
I was previously using a Javascript fix but encountered problems when the browser was caching iframes and then pre-loading them when I use the backarrow before running the css-fixing js, even though I was setting the src attribute of the iframes <i>after</i> the css-fixing code completed in order to delay it. The delayed src attribute did work when the page was not reached via back arrow, but when it was, it lead to a screwed up appearance while the iframes loaded because the css-fixing code was held up by the iframes. Perhaps there is a way around this, but nonetheless a css-only solution desirable if it does what you need.
</p>

<p> This approach does not work for background <i>images</i>--only solid background <i>colors</i>--unless you don't mind the scrolling content moving against a static image.
</p>

<p>"Flexible" means that the height of content in each column can be different, and the widths can be percentages. Here is an uneven <a href="/multicolumn">3-column demonstration</a>, though it should apply for any <i>n</i>.  
</p>

<p>
Given <i>n</i> columns, and the width (in percentage if you want) you want each to occupy, first create an empty div for each that will serve as their respective backgrounds (colors). Order shouldn't matter.  Continuing the <i>n=3</i> example:
</p>

<pre class="prettyprint codebox">
    &lt;div id="leftbg"&gt;&lt;/div&gt;
    &lt;div id="middlebg"&gt;&lt;/div&gt;
    &lt;div id="rightbg"&gt;&lt;/div&gt;
</pre>

with the following styles:


<pre class="prettyprint codebox">
#leftbg {
    background-color: green;
    height: 100%;
    width: 14%;
    position: fixed;
    top: 0;
    left: 0;
}

#rightbg {
    background-color: blue;
    height: 100%;
    width: 24%;
    position: fixed;
    top: 0;
    right:0;
}

#middlebg {
    background-color: red;
    height: 100%;
    width:62%;
    position: fixed;
    top: 0;
    right: 24%;
    left: 14%; 
}
</pre>

Note for example, that the <b>left</b> style attribute of <b>#middlebg</b> is the same as the <b>width</b> attribute of <b>#leftbg</b>, and so on.

<p>
Then float content containers with each column's content above each of those backgrounds.
</p>

<pre class="prettyprint codebox">
&lt;div id="leftcontainer"&gt;
    &lt;div id="leftcontent"&gt;&lt;p&gt;hello&lt;/p&gt;&lt;/div&gt;
&lt;/div&gt;

&lt;div id="middlecontainer"&gt;
    &lt;div id="middlecontent"&gt;&lt;p&gt;hello&lt;/p&gt;&lt;/div&gt;
&lt;/div&gt;
</pre>

<p>with:</p>

<pre class="prettyprint codebox">
#leftcontainer{
    width: 14%;
    position: relative;
    float: left;
}
#middlecontainer{
    width: 62%;
    position: relative;
    float: left;
}
</pre>

<p>
Note the widths are the same as their respective background divs. The containers and content have no background. It's just text/whatever that is made to float over the background divs.
<p>

</p>
At this point, aside from the use of absolute positioning, you can effectively treat each column an isolated page.
</p>
{% endblock %}

FlaskApp/templates/blogs/7-20-14.html
{% extends "blog.html" %}
{% block post %}
<h2>Storing boolean information in individual bits in C</h2>

In my current webscraping/Big Data/thesaurus project (that's only loosely related to <a href="/synonyms">this</a>, I was originally representing the graph with an <b>NxN</b> connectrix instead of as linked nodes.  It later became clear that that wasn't the way to go, due the low edge density.  Since edges were non-weighted, they could only take on one of two values, and so only one bit is needed to represent it in a connectrix.  The best immediately available option, an unsigned char, would use 8 times as much space as is theoretically needed.  
</p>

<p>
Of course, computer hardware doesn't lend itself to a single-bit <i>type</i>.  However, the idea of an <i>array</i> of single bits makes a bit more sense, even if bits can't technically be accessed or changed directly in the same way as a byte.  I ended up implementing a <b>bitsarr</b> that can store an array of either 1-, 2-, or 4-bit values, since those all divide the number of bits in a byte.  I haven't done any testing yet to see how much the extra work in accessing and writing slows it down compared to a proper C array, but there's no doubt it can save space.  So even though I'm not currently using it, it was an interesting experiment that I figured was worth mentioning.
</p>

<p>Underneath the hood, a <b>bitsarr</b> is an array of unsigned chars.  To store 0 or 1 (when numbits is ONE) at index 13, simply do the bitwise operations necessary to set or unset the 5th bit in the 2nd unsigned char 'bucket'.
</p>

<pre class="prettyprint codebox">
#include &lt;stdio.h&gt;
#include &lt;stdlib.h&gt;
#define BYTE 8

typedef enum {ONE=1, TWO=2, FOUR=4} numbits;

typedef struct bitsarr{
    unsigned char* buckets;
    numbits n;
} bitsarr;


bitsarr new_bitsarr(int size, numbits n)
{
    int b = sizeof(unsigned char)*BYTE;
    int numbuckets = (size*n + b - 1)/b;
    bitsarr ret;  
    ret.buckets = malloc(sizeof(ret.buckets)*numbuckets);
    ret.n = n;
    return ret;
}
void bitsarr_delete(bitsarr xp)
{
    free(xp.buckets);
}

void bitsarr_set(bitsarr *xp, int index, int value)
{
    int buckdex, innerdex;
    buckdex = index/(BYTE/xp-&gt;n);
    innerdex = index%(BYTE/xp-&gt;n);
    xp-&gt;buckets[buckdex] = (value &lt;&lt; innerdex*xp-&gt;n) | ((~(((1 &lt;&lt; xp-&gt;n) - 1) &lt;&lt; innerdex*xp-&gt;n)) & xp-&gt;buckets[buckdex]);

    //longer, readable version

    /*unsigned int width, width_in_place, zeros, old, newbits, new;
    width = (1 << xp->n) - 1; 
    width_in_place = width << innerdex*xp->n;
    zeros = ~width_in_place;
    old = xp->buckets[buckdex];
    old = old & zeros;
    newbits = value << innerdex*xp->n;
    new = newbits | old;
    xp->buckets[buckdex] = new; */

}

int bitsarr_get(bitsarr *xp, int index)
{
    int buckdex, innerdex;
    buckdex = index/(BYTE/xp->n);
    innerdex = index%(BYTE/xp->n);
    return ((((1 << xp->n) - 1) << innerdex*xp->n) & (xp->buckets[buckdex])) >> innerdex*xp->n;

    //longer, readable version

    /*unsigned int width = (1 << xp->n) - 1; 
    unsigned int width_in_place = width << innerdex*xp->n;
    unsigned int val = xp->buckets[buckdex];
    unsigned int retshifted = width_in_place & val;
    unsigned int ret = retshifted >> innerdex*xp->n;
    return ret; */
}

int main() //test
{
    bitsarr x = new_bitsarr(100, FOUR);
    for(int i = 0; i<16; i++)
        bitsarr_set(&x, i, i);
    for(int i = 0; i<16; i++)
        printf("%d\n", bitsarr_get(&x, i));
    for(int i = 0; i<16; i++)
        bitsarr_set(&x, i, 15-i);
    for(int i = 0; i<16; i++)
        printf("%d\n", bitsarr_get(&x, i));
    bitsarr_delete(x);
}
</pre>

<p>
One thing to note about the above implementation is that it assumes the user will not try to set an index to a value outside the range.  E.g., if the user creates a <b>bitsarr</b> to store 4-byte values, and tries to set an index to 17, the value at that index will not overflow unless it happens to be the last value blocked into an unsigned char 'bucket'.  Otherwise, the value at the subsequent index will be corrupted.
</p>
{% endblock %}

FlaskApp/templates/blogs/7-26-14.html
{% extends "blog.html" %}
{% block post %}
<h2>July 26: MySQL 5.6 partition selection feature as alternative to 'LIMIT offset, count'</h2>
<p>
When processing tens of millions of MySQL rows with text fields, you can't load them all into memory at once.  So, you need a way of systematically loading pieces of it one at a time.  The simplest, but not best performing way would be something like this (100,000 at a time):
</p>
<pre class="prettyprint codebox">
SELECT &lt;fields&gt; FROM &lt;table&gt; LIMIT 0, 100000;
SELECT &lt;fields&gt; FROM &lt;table&gt; LIMIT 100000, 100000;
SELECT &lt;fields&gt; FROM &lt;table&gt; LIMIT 200000, 100000;
...
</pre>
<p>
However, the bigger that offset is, the more work MySQL has to do to know where to begin holding on to rows to send back.  But as <a href="http://explainextended.com/2009/10/23/mysql-order-by-limit-performance-late-row-lookups/">this article</a> explains, this can be improved significantly with a JOIN approach--select the desired range of ids, and JOIN that with the other fields.  It's worth noting that this approach can lead to rows coming back in a different order, but if the goal is to iterate through <i>all</i> the rows and perform non-sequential computations on them, that wouldn't matter.
</p>

<p>
If you really have tens of millions of rows, that approach will still cost you seconds or minutes (better than minutes or hours).  While table partitioning has been available since 5.1, there's a new feature in 5.6 that allows for manually limiting queries to a partition specified by number.  What's nice about this is that--at least with MyISAM tables, though presumably InnoDB as well--it doesn't take measurably longer to select from the 80th partition than from the 5th, even if each partition has hundreds of thousands of rows.
</p>


<p>
One way to use the feature would be to select entire partitions at a time for processing. This should be safe as long as you know the partitions won't get too large (and depending on the type of partition, they may or may not be roughly equal in size).  But with a little more work, you can systematically use the feature to get the same <i>nth</i> row as the naive approach with speed improved by orders of magnitude.  Since COUNT queries with no WHERE clause are quite fast on whole partitions of MyISAM tables, you would simply need to add the sizes of sequential partitions until partition <i>i</i>, where you're at row <i>m</i>, just over <i>n</i>, and then select from that last partition with the appropriate offset.
</p>

<pre class="prettyprint codebox">
SELECT &lt;fields&gt; FROM &lt;table&gt; partition (p&lt;i-1&gt;) LIMIT &lt;m-n&gt;, 1
</pre>

<p>
But again, if all you need to do is analyze every row in reasonably sized chunks, all that trouble is unnecessary and it's quite straightforward to just select one whole partition at a time.
</p>

<p>
I wrote a simple bash script to compare query times for selecting a single row at various 'depths' into the table using the three different methods.  The results and script are below.  I don't know exactly what causes the severe spike in the naive method about halfway through the chart, but I'm guessing it's due to the amount of RAM on my machine.  This is on a hash-partitioned MyISAM table with about 21 million rows and 100 nearly equal partitions.  Instead of explaining exactly what the test was in words, I'll let the short bash script speak for itself.  Suffice it to say, if the <i>nth</i> partition is rows <i>a</i> through <i>b</i>, it is in general much faster to select the <i>nth</i> partition than to use 'LIMIT a, b-a'.
</p>

<img src="{{url_for('static', filename='img/spreadsheet.png')}}" id="chart"></img>
<pre class="prettyprint codebox">
#!/bin/bas
#!/bin/bash

part_start=0
small_offset=1000

function nano_time() {
    echo "$(($(date +'%s * 1000 + %-N / 1000000')))"
}

for i in {0..99}; do
    partsize_result="$(mysql --login-path=local $1 -e "select count(*) from $2 partition (p$i);")"
    partsize=`echo $partsize_result | cut -d ' ' -f2` 
    offset=`expr $small_offset + $part_start`

    start=$(nano_time)
    res=$(mysql --login-path=local $1 -e "select id, author from $2 limit $offset, 1;")
    finish=$(nano_time)
    naive_elapsed=`expr $finish - $start`

    start=$(nano_time)
    res=$(mysql --login-path=local $1 -e "select l.id, author from ( select id from $2 limit $offset, 1 ) o join $2 l on l.id = o.id; ")
    finish=$(nano_time)
    join_elapsed=`expr $finish - $start`
    #join_way=`expr $join_way + $elapsed`

    start=$(nano_time)
    res="$(mysql --login-path=local $1 -e "select id, author from $2 partition (p$i) limit $small_offset, 1;")"
    finish=$(nano_time)
    part_elapsed=`expr $finish - $start`

    echo $i, $part_elapsed, $join_elapsed, $naive_elapsed
    part_start=`expr $part_start + $partsize`
done
</pre>
{% endblock %}

FlaskApp/templates/blogs/7-5-14.html
{% extends "blog.html" %}
{% block post %}
<h2>Neo4j's Cypher and Shortest Paths</h2>
<p>
When I originally set out to make my <a href="/synonyms">synonym path</a> webapp, 
graph databases were something I knew little about, though I 
assumed they existed.  I was already familiar with tabular 
databases like MySQL, and recognized that they aren't ideal for
representing graphs.  It didn't take long to find out that Neo4j
was the go-to graph database.
</p>
<p>
Since this is a Flask site, and since I was in an overall Python
phase at the time, I didn't initially consider an alternative
to using a Python API to Neo4j.  The main two options were 
<a href="https://pypi.python.org/pypi/neo4jrestclient/">Neo4j Python REST Client</a> and 
<a href="http://nigelsmall.com/py2neo/1.6/">Py2neo</a>.  I tried out both.  I was able to create
and query a graph easily enough, but was unable to find anything
in the respective docs about shortest paths, which is what I needed
in order to find shortest paths between two synonym nodes in my thesaurus 
graph.
</p>
<p>So the next step was to learn Cypher, Neo4j's counterpart to SQL. Like
most database API's, Py2neo supports writing your own queries directly.  
Fortunately, Cypher did have a built in shortestPath feature, with the option
to limit the length.  For instance, my Python code to find a synonym path
shorter than 100 looked like this:


<pre class="prettyprint codebox">

def shortest_path_neo(a, b):
    a = g.conn.get_indexed_node("worddex", "word", a)
    b = g.conn.get_indexed_node("worddex", "word", b)
    if not a and b: return None
    #the important part
    query_string = "START beginning=node(%d), end=node(%d) 
                    MATCH p = shortestPath(beginning-[*..100]-end) 
                    RETURN p" % (a._id, b._id)
    result = neo4j.CypherQuery(g.conn, query_string).execute()
    if not len(result): return None
    p = result[0].p
    ret = []
    return [node["word"] for node in p.nodes]
</pre>

<p>
This performed well and I built the initial version of the webapp upon it. However, I soon got the idea of letting users block certain words from being included in paths--essentially find shortest paths in a subgraph consisting of all words except for a few they choose to leave out.   Since so few people are actually using this webapp, it probably would have been a decent practical solution to simply remove the given words from the database, perform the query,  and then add them back in.  But clearly that's a bad solution from a theoretical standpoint, because if there were ever lots of users at the same time, it could potentially lead to inconsistent, incorrect behavior.
</p>

<p>
Unfortunately, hours of searching eventually revealed that Cypher does notyet support shortest path queries with any kind of constraint on the nodes in the path.  But since the webapp does not involve any writes to the thesaurus data, and since it's no more than a MB or two in size, all I really needed was a data structure sitting in memory that could be shared among threads.  To balance speed of code with the availability of HTTP server libraries, I ended up going with Java and Apache Tomcat.
</p>

<p>
I implemented a standard link-based graph, with a trie as an index into the nodes (though a HashMap would have worked just as well).  Visited nodes and nodes for words the user wants to avoid are added to a HashSet for quick containment checks, since it must be done at every iteration in the BFS. Here is <b>Wordnode.shortestPath</b>: 
</p>

<pre class="prettyprint codebox">
public LinkedList&lt;String&gt; shortestPath(Wordnode dest, int limit, HashSet&lt;Wordnode&gt; avoids)
{
    HashSet&lt;Wordnode&gt; visited = new HashSet&lt;&gt;();
    HashMap&lt;Wordnode, Wordnode&gt; previous = new HashMap&lt;&gt;();
    LinkedList&lt;Wordnode&gt; q = new LinkedList&lt;Wordnode&gt;();
    previous.put(this, null);
    if(!avoids.contains(this))
        q.add(this);
    Wordnode curr = null;
    boolean found = false;
    while(!q.isEmpty() && !found)
    {
        curr = q.removeLast();
        visited.add(curr);
        if(curr == dest)
            found = true;
        else
        {
            for(Wordnode n: curr.neighbors)
            {
                if(!visited.contains(n) && !avoids.contains(n))
                {
                    q.addFirst(n);
                    if(!previous.containsKey(n))
                        previous.put(n, curr);
                }
            }
        }
    }
    if(!found)
        return null;
    LinkedList&lt;String&gt; ret = new LinkedList&lt;&gt;();
    while(curr != null)
    {
        ret.addFirst(curr.word);
        curr = previous.get(curr);
    }
    return ret;
}
</pre>
<p>
For now, this is a fine solution.  With over 20 thousand nodes in the graph, worst case (non-existant path) queries usually take about a tenth of a second on the server, which is actually a bit less than what I recall the Neo4j implementation taking.  With that said, I have since discovered
a couple potential alternative solutions to explore down the road.  One would be to learn Neo4j's official Traversal Framework Java API.  The other would be to checkout Datomic, an idea I got from <a href="http://hashrocket.com/blog/posts/using-datomic-as-a-graph-database">this article</a> on using Datomic as a graph database for a shortest path webapp quite similar to mine.
</p>
{% endblock %}

FlaskApp/templates/blogs/8-1-14.html
{% extends "blog.html" %}
{% block blogexternal %}
    <link href="{{ url_for('static', filename='css/blogs/8-1-14.css') }}" rel="stylesheet">
    <script type="text/javascript" src="{{ url_for('static', filename='js/blogs/8-1-14.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/widgets/spin.min.js') }}"></script>
{% endblock %}
{% block post %}
<h2>Didyoumeanthis</h2>
<p> Since I have recently become interested in the field of data science, I was watching <a href="https://www.youtube.com/watch?v=gUTuESHKbXI">this</a> talk by Daniel Tunkeland of LinkedIn about the interviewing process for data scientists.  He was talking about potential coding questions to ask, and one was to try to segment a string with no spaces into possible word sequences.  This happens to be an especially good use case for tries (and dynamic programming), which I've always liked working with, and since I generally feel guilty if I go months without writing anything non-trivial in one of the languages I've chosen to maintain knowledge of, I decided to implement it client-side with Javascript (which makes sense, after all).  Try it out:
</p>
    <div id="form">
        <input id="string" type="text" value="nowherenow">
        <button class="blueButton" id="submit">did you mean</button>
        <div id="result">
            <b><ul id="resultList"></ul> </b>
        </div>
    </div>
<p>When representing set data or key-value data on strings, tries aren't a bad choice.  However, in many situations involving simple look-ups exposed by a basic map interface, there's a pretty good chance some hash-based implementation will be faster and maybe more memory efficient than a regular trie.  But in this situation, the trie is used for more than a representation of a set.  The internal structure of the trie is exploited to do all necessary lookups in constant time.  
</p>
<p>
For example, if we had the string "nowhere", we can check whether "n" is a word in constant time.  Then, when we check whether "no" is a word, we don't traverse the trie from the root again--instead, we keep around a reference to the node for "n" and go from there. And if we use memoization, then we only have to move from a parent to child O(n^2) times in total, which dominates in the runtime complexity.
<p>Of course, <i>generating</i>  and outputting individually (not just counting) all possible segmentations has exponential worst case runtime.  If somehow every substring was in the dictionary, then there would be 2^(n-1) valid segmentations.
</p>
<p>Then again, what if we make the requirement that the strings must be comprised of words from the language.  Then, if our language is {"ab", "ba"} (or any language where all words are of the same legnth), or something like {"ab", "abb"}, then the number of valid segmentations is always one.  I'm not sure if this is a well studied math problem (not quite sure what I'd google to find out).  However, I got curious about the English language case, so I ran some tests with the similar Javascript code using Rhino.
</p>

<img src="{{url_for('static', filename='img/segmentation.png')}}" id="chart"></img>
{% endblock %}

FlaskApp/templates/blogs/8-13-14.html
{% extends "blog.html" %}
{% block post %}
<h2>Tracking Down Bugs in Git's Source Code</h2>


<p>
Even great software has bugs, but I honestly didn't expect to be debugging git anytime soon.  To go ahead and spoil the ending--it turns out I should have just upgraded from 1.9.1 to 2, but I mistakenly assumed that Mint 17 would have the latest.  It all started when I decided to try using vimdiff as my diff tool. I followed <a href="http://technotales.wordpress.com/2009/05/17/git-diff-with-vimdiff/">this tutorial</a> to configure it.  Upon trying to use vimdiff via git, I got this error:
</p>
<pre class="codebox">
fatal: cannot exec 'git_diff_wrapper': Bad address
external diff died, stopping at HEAD:switch-monitor.sh.
</pre>

<p>
Attempts at finding similar errors on google yielded nothing, which is usually a sign that you're in for a bad time.
</p>

<p>So I decided to clone git's source and use grep to try to find where this error message is being outputted.  Unfortunately, it was not as simple as grepping the first line with a regex in place of 'git_diff_wrapper'.  This is because the text "fatal" and "cannot exec" never occur on the same line in git's source, and "Bad address" doesn't occur in git's source <i>at all</i> (only in one test shell script).
</p>

<p>After digging around in the source, I found that these three components were being pieced together in separate places (a.k.a. modularity).  Additionally, the text "Bad address" was coming from from the <b>strerror</b> message for <b>EFAULT</b>.

<p>This code is run when a system exec call returns (hence an error).</p>

<pre class="codebox prettyprint">
if (errno == ENOENT) {
        if (!cmd->silent_exec_failure)
                error("cannot run %s: %s", cmd->argv[0],
                        strerror(ENOENT));
        exit(127);
} else {
        die_errno("cannot exec '%s'", cmd->argv[0]);
}
</pre>

<p> and it turns out that in the course of function calls within <b>die_errno</b>, "fatal: " is prepended, and the <b>strerror</b> message is appended.  All of the above occur in a child process spawned below:
<p>

<pre class="codebox prettyprint">
if (run_command_v_opt_cd_env(argv.argv, RUN_USING_SHELL, NULL, env.argv))
        die(_("external diff died, stopping at %s"), name);
</pre>


<p>
<b>EFAULT</b> is often caused by the absence of a pointer to NULL at the end of the argument list.  The call to execvp occurs within <b>sane_execvp</b>, but there's little going on there besides the call.  Thus I decided to look in <b>prepare_shell_cmd</b> for the culprit.  Here is the greater context:
</p>
<pre class="codebox prettyprint">
static int execv_shell_cmd(const char **argv)
{
    const char **nargv = prepare_shell_cmd(argv);
    trace_argv_printf(nargv, "trace: exec:");
    sane_execvp(nargv[0], (char **)nargv);
    free(nargv);
    return -1;
}
</pre>
<p>and here is <b>prepare_shell_cmd</b>:</p>

<pre class="codebox prettyprint">
static const char **prepare_shell_cmd(const char **argv)
{
    int argc, nargc = 0;
    const char **nargv;

    for (argc = 0; argv[argc]; argc++)
        ; /* just counting */
    /* +1 for NULL, +3 for "sh -c" plus extra $0 */
    nargv = xmalloc(sizeof(*nargv) * (argc + 1 + 3));

    if (argc &lt; 1)
        die("BUG: shell command is empty");

    if (strcspn(argv[0], "|&;&lt;&gt;()$`\\\"' \t\n*?[#~=%") != strlen(argv[0])) {
#ifndef GIT_WINDOWS_NATIVE
        nargv[nargc++] = SHELL_PATH;
#else
        nargv[nargc++] = "sh";
#endif
        nargv[nargc++] = "-c";

        if (argc &lt; 2)
            nargv[nargc++] = argv[0];
        else {
            struct strbuf arg0 = STRBUF_INIT;
            strbuf_addf(&arg0, "%s \"$@\"", argv[0]);
            nargv[nargc++] = strbuf_detach(&arg0, NULL);
        }
    }

    for (argc = 0; argv[argc]; argc++)
        nargv[nargc++] = argv[argc];
    nargv[nargc] = NULL;

    return nargv;
}
</pre>

<p>but I was unable to spot the problem here.  User's on stackoverflow recommended I run the git command under strace and valgrind.  The results of both suggested that the problem was indeed a bug in git.</p>
<p>As relived as I was when the problematic code was spotted, I must admit I was disappointed that I didn't get to pinpoint the problematic code myself. A friendly and knowledgable stackoverflow user <a href="http://stackoverflow.com/questions/25272721/execvp-call-in-gits-source-for-external-shell-cmd-returns-efault-bad-address">beat me to it</a></p>

<pre class="codebox prettyprint">
const char *spawn_arg[10];
int retval;
const char **arg = &spawn_arg[0];
struct diff_queue_struct *q = &diff_queued_diff;
const char *env[3] = { NULL };
char env_counter[50];
char env_total[50];

if (one && two) {
        struct diff_tempfile *temp_one, *temp_two;
        const char *othername = (other ? other : name);
        temp_one = prepare_temp_file(name, one);
        temp_two = prepare_temp_file(othername, two);
        *arg++ = pgm;
        *arg++ = name;
        *arg++ = temp_one->name;
        *arg++ = temp_one->hex;
        *arg++ = temp_one->mode;
        *arg++ = temp_two->name;
        *arg++ = temp_two->hex;
        *arg++ = temp_two->mode;
        if (other) {
                *arg++ = other;
                *arg++ = xfrm_msg;
        }
} else {
        *arg++ = pgm;
        *arg++ = name;
}
*arg = NULL;
</pre>

<p>If <b>one</b>, <b>two</b>, and <b>other</b> all evaulate to true, then <b>spawn_arg</b>, of size 10, is filled with 10 arguments, <i>then</i> the terminating NULL.  That leaves the possibility of that NULL getting overwritten.</p>



{% endblock %}

FlaskApp/templates/blogs/post.html
{% extends "blog.html" %}
{% block main_content %}
    <h2>{{ post.title }}</h2>
    <div id="blogtaglist">
        {% for tag in tags %}
        <span class="blogtag">
            <a href="{{ url_for('blog.tag', tagname=tag.name) }}">
                {{ tag.name }}
            </a>
        </span>
        {% endfor %}
    </div>
    {{ post.text|safe }}
{% endblock %}

{% block resource_list %}
        <h3>Index</h3>
        <ul>
            {% for p in index %}
            <li><a class="bloglink" href="{{url_for('blog.post', date=p.date)}}">{{p.date|blog_date~": "~p.title}}</a></li>
            {% endfor %}
        </ul>
{% endblock %}

FlaskApp/templates/blogs/tag.html
{% extends "blog.html" %}
{% block main_content %}
<h2>tag: {{tag.name}}</h2>
<ul>
    {% for p in posts %}
    <li class="postlist">
        <a class="bloglink" href="{{url_for('blog.post', date=p.date)}}">{{p.date|blog_date~": "~p.title}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

{% block resource_list %}
        <h3>Tags</h3>
        <ul>
            {% for t in taglist %}
            <li>
            <span class="blogtag">
                <a  href="{{url_for('blog.tag', tagname=t.name)}}">{{t.name}}</a>
            </span>
            </li>
            {% endfor %}
        </ul>
{% endblock %}